credentials/urls.py
from . import views
from django.urls import path

app_name = 'credentials'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('register/', views.register, name='register'),
    path('logout/', views.logout, name='logout'),
]

store/urls.py
from . import views
from django.urls import path

app_name = 'schoolstore'

urlpatterns = [
    path('', views.home, name='home'),
    path('order/', views.place_order.as_view(), name='order'),
    path('ajax/get_courses/', views.get_courses, name='ajax_get_courses'),
    path('sucess/',views.sucess,name='sucess')

]

storeproject/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from storeproject import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('credentials/', include('credentials.urls')),
    path('', include('store.urls'))

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

credentials/models.py
from django.db import models

# Create your models here.

store/models.py
from django.db import models

# Create your models here.


from django.db import models


# Create your models here.
class Department(models.Model):
    dept_name = models.CharField(max_length=100)
    wiki_page = models.URLField()

    def __str__(self):
        return self.dept_name


class Courses(models.Model):
    course_name = models.CharField(max_length=50)
    course_dept = models.ForeignKey(Department, on_delete=models.CASCADE)

    def __str__(self):
        return self.course_name


class Materials(models.Model):
    item = models.CharField(max_length=50)

    def __str__(self):
        return self.item


class Order(models.Model):
    name = models.CharField(max_length=100)
    date_of_birth = models.DateField()
    age = models.IntegerField()
    GENDER_CHOICE = [('m', "Male"), ('f', "Female"), ('o', "Others")]
    gender = models.CharField(choices=GENDER_CHOICE, max_length=1)
    phone_number = models.IntegerField()
    email = models.EmailField()
    address = models.TextField()
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    course = models.ForeignKey(Courses, on_delete=models.CASCADE)
    PURPOSES = [('eq', "Enquiry"), ('po', "Place Order"), ('r', "Return")]
    purpose = models.CharField(max_length=2, choices=PURPOSES)
    materials = models.ManyToManyField(Materials)

store/forms.py
from .models import Order, Courses, Department
from django import forms


class OrderForm(forms.ModelForm):
    class Meta:
        model = Order


        fields = '__all__'
        widgets = {
            'department': forms.Select(attrs={'class': 'form-control'}),
            'course': forms.Select(attrs={'class': 'form-control'}),
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'date_of_birth': forms.DateInput(format='%d/%m/%Y',attrs={'class': 'form-control','type': 'date'}),
            'age': forms.NumberInput(attrs={'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
            'phone_number': forms.NumberInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'address': forms.Textarea(attrs={'class': 'form-control'}),
            'purpose': forms.Select(attrs={'class': 'form-control'}),
            'materials':forms.CheckboxSelectMultiple()

        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['course'].queryset = Courses.objects.none()

        if 'department' in self.data:
            try:
                dept_id = int(self.data.get('department'))
                self.fields['course'].queryset = Courses.objects.filter(course_dept=dept_id).order_by('course_name')
            except(ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['course'].queryset = self.instance.department.course_set.order_by('course_name')

credentials/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth, messages


# Create your views here.

def register(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        c_password = request.POST['c_password']

        if password == c_password:
            if User.objects.filter(username=username):
                messages.info(request, "username allready exists")
                return redirect('credentials:register')


            else:
                user = User.objects.create_user(username=username,
                                                password=password)
                user.save()
                print("user created")
                return redirect('credentials:login')
        else:
            messages.info(request, 'Password dose not match')
            return redirect('credentials:register')
    return render(request, 'register.html')


def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('/')
        else:
            messages.info(request, "Invalid credentials")
            return redirect('credentials:login')

    return render(request, 'login.html')


def logout(request):
    auth.logout(request)
    return redirect('credentials:login')

store/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from .forms import OrderForm
from .models import Courses
from django.views.generic.edit import CreateView


# Create your views here.
def home(request):
    return render(request, 'home.html')


def sucess(request):
    return render(request, 'sucess.html')


class place_order(CreateView):
    form_class = OrderForm
    template_name = 'order.html'


    def form_valid(self, form):
        form.save()
        return redirect('/sucess')


def get_courses(request):
    dept_id = request.GET.get('department')
    courses = Courses.objects.filter(course_dept=dept_id).order_by('course_name')
    return render(request, 'course_options.html', {'courses': courses})

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta name="description" content="{% block metadescription %} {% endblock %}">
    <meta charset="UTF-8">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'styles/style.css' %}">


</head>
<body>


{% include 'navbar.html' %}

{% block content %}
{% endblock %}


</div>
</body>
</html>

templates/course_options.html
<option value="">---------</option>
{% for course in courses %}
<option value="{{ course.pk }}">{{ course.course_name }}</option>
{% endfor %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
home page
{% endblock %}

{% block title %}
EduStore
{% endblock %}

{% block content %}
<div class="container">
<div class=" p-5 mb-4 bg-light rounded-3">
  <div>
    <IMG SRC="{% static 'classroom.jpg' %}" style="height:200px;width:1056px">
  </div>
      <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">Place Order</h1>
        <p class="col-md-8 fs-4">Place your order or send for a enquiry</p>
        <a href="{% url 'schoolstore:order' %}"><button class="btn btn-primary btn-lg" type="button">Place order</button></a>
      </div>
    </div>
</div>




{% if successful %}
<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Order Sucess</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Order has been successfully creted
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Ok</button>
      </div>
    </div>
  </div>
</div>
<script type="text/javascript">
        $(document).ready(function(){
            $("#staticBackdrop").modal('show');
        });

</script>
ghgghgjhgjhgjhgjhgvjhv
{% endif %}
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
login page
{% endblock %}

{% block title %}
LogIn
{% endblock %}

{% block content %}

<div class="container">
    <div class="card" style="width: 30rem;">
        <img src="{% static 'classroom.jpg' %}"style="height:350px;width:480px;" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">LogIn</h5>
            <p class="card-text">
            <form action="{% url 'credentials:login' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">username</label>
                    <input type="text" class="form-control" id="username" placeholder="Enter username" name="username">
                </div>
                <div class="form-group">
                    <label for="Password">Password</label>
                    <input type="password" class="form-control" id="Password" placeholder="Password" name="password">
                </div>

                <button type="submit" class="btn btn-primary">Login</button>


            </form>
            </p>
        </div>
        <div class="card-footer ">
             New user? Register here-
                <a href="{% url 'credentials:register' %}">
                    Register
                </a>
            {% for msg in messages%}
            <p> - {{msg}}</p>
            {% endfor%}
        </div>
    </div>


</div>

{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="#">Scrodinger Store</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            {% if user.is_authenticated %}
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'schoolstore:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item nav-link">
                Heloo {{user.username}}
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'credentials:logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'credentials:login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'credentials:register' %}">Register</a>
            </li>


            {% endif%}


            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="true">
                    Department
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                    {% for department in departments %}
                    <a class="dropdown-item" href="{{department.wiki_page}}">{{department.dept_name}}</a>
                    <div class="dropdown-divider"></div>
                    {% endfor %}
                </div>
            </li>
        </ul>
    </div>
</nav>

templates/order.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
order form
{% endblock %}

{% block title %}
Order
{% endblock %}

{% block content %}
<div class="order container">
    <div>
        <img src="{% static 'A.jpg' %}" style="height:300px;width:1110px;">
    </div>
    <div class=" p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
            <h1 class="display-5 fw-bold">APPLICATION FORM</h1>
            <p class="col-md-8 fs-4">
            <form method="POST" enctype="multipart/form-data" id="orderForm"
                  data-courses-url="{% url 'schoolstore:ajax_get_courses' %}" action="{% url 'schoolstore:order' %}">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col">
                        {{ form.name.errors }}
                        {{ form.name.label_tag }}
                        {{ form.name }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col">
                        {{ form.date_of_birth.errors }}
                        {{ form.date_of_birth.label_tag }}
                        {{ form.date_of_birth }}
                    </div>
                    <div class="col">
                        {{ form.age.errors }}
                        {{ form.age.label_tag }}
                        {{ form.age }}
                    </div>
                    <div class="col">
                        {{ form.gender.errors }}
                        {{ form.gender.label_tag }}
                        {{ form.gender }}

                    </div>
                </div>
                <div class="form-row">
                    <div class="col">
                        {{ form.department.errors }}
                        {{ form.department.label_tag }}
                        {{ form.department }}
                    </div>
                    <div class="col">
                        {{ form.course.errors }}
                        {{ form.course.label_tag }}
                        {{ form.course }}
                    </div>
                    <div class="col">
                        {{ form.purpose.errors }}
                        {{ form.purpose.label_tag }}
                        {{ form.purpose }}

                    </div>
                </div>
                <div class="form-row">
                    <div class="col">
                        {{ form.phone_number.errors }}
                        {{ form.phone_number.label_tag }}
                        {{ form.phone_number }}
                    </div>
                    <div class="col">
                        {{ form.email.errors }}
                        {{ form.email.label_tag }}
                        {{ form.email }}

                    </div>
                </div>
                <div class="form-row">
                    <div class="col">
                        {{ form.address.errors }}
                        {{ form.address.label_tag }}
                        {{ form.address }}
                    </div>
                    <div class="col">
                        {{ form.materials.errors }}
                        {{ form.materials.label_tag }}
                        {{ form.materials }}
                    </div>
                </div>
                <div class="form-row">
                    <div class="col">
                        <button class="btn btn-primary btn-lg" type="submit">Submit order</button>
                    </div>
                </div>
            </form>
            </p>
            <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
            <script>
    $("#id_department").change(function () {
      var url = $("#orderForm").attr("data-courses-url");
      var departmentId = $(this).val();
      $.ajax({
        url: url,
        data: {
          'department': departmentId
        },
        success: function (data) {
          $("#id_course").html(data);
        }
      });

    });







            </script>

        </div>
    </div>

</div>

{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
Register page
{% endblock %}

{% block title %}
Register
{% endblock %}

{% block content %}

<div class="container">

    <div class="card" style="width: 30rem;">
        <img src="{% static 'backgroundimage.png' %}" style="height:400px;" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Register</h5>
            <p class="card-text">
            <form action="{% url 'credentials:register' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">username</label>
                    <input type="text" class="form-control" id="username" placeholder="username" name="username">
                </div>
                <div class="form-group">
                    <label for="Password">Password</label>
                    <input type="password" class="form-control" id="Password" placeholder="Password"
                           name="password">
                </div>
                <div class="form-group">
                    <label for="CPassword">Password</label>
                    <input type="password" class="form-control" id="CPassword" placeholder="Cnofirm Password"
                           name="c_password">
                </div>

                <button type="submit" class="btn btn-primary">Login</button>
            </form>
            </p>
        </div>
        <div class="card-footer text-muted">
            {% for msg in messages%}
            {{msg}}
            {% endfor%}
        </div>
    </div>

</div>

{% endblock %}

templates/sucess.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
Sucess form submition
{% endblock %}

{% block title %}
sucess
{% endblock %}

{% block content %}
<div class="container">
    <div>
        <img src="{% static 'library.png' %}" style="height:200px;width:1110px;">
    </div>
    <div class=" p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
            <h1 class="display-5 fw-bold">Success</h1>
            <p class="col-md-8 fs-4">Your order placed successfully sent. </p>
            <p>-Thankyou</p>
            <a href="{% url 'schoolstore:home' %}">
                <button class="btn btn-primary btn-lg" type="button">Return to home</button>
            </a>
        </div>
    </div>
</div>
{% endblock %}